allow name with space in name

diff --git a/bin/ec2 b/bin/ec2
--- a/bin/ec2
+++ b/bin/ec2
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 . $EC2_SCRIPT_HOME/conf/.ec2-default.props
 
 # Init variables
@@ -40,7 +40,7 @@ while getopts "u:k:c:n:ixh" opt; do
       exit 1
       ;;
     \?)
-      echo "\033[1;32mInvalid option: -$OPTARG\033[0m" >&2
+      echo -e "\033[1;32mInvalid option: -$OPTARG\033[0m" >&2
       ;;
   esac
 done
@@ -89,7 +89,7 @@ else
 fi
 
 # Print region info
-echo "\033[33mRegion: $region\033[0m"
+echo -e "\033[33mRegion: $region\033[0m"
 
 # Print info and quit
 if [ "$infoOpt" = "Y" ]
@@ -105,30 +105,38 @@ hostname="`echo "$hosts" | awk 'BEGIN { FS = "\t" } ; { print $2 }'`"
 
 if [ "$nameOpt" != "" ]
 then
-
 	index=0
-	for i in $name
+
+	OIFS="${IFS}"
+	NIFS=$'\n'
+	
+	IFS="${NIFS}"
+
+	for i in `echo "$name"`
 	do
+		IFS="${OIFS}"
 		index=`expr $index + 1`
 		if [ "$nameOpt" = "$i" ]
 		then 
-			range="$index"	
+			export range="$index"	
 		fi
-	done
+		IFS="${NIFS}"
+	done 
+	IFS="${OIFS}"
 
 	if [ "$range" = "" ]
 	then
-		echo "Host $nameOpt not found" 
+		echo -e "\033[31;2mHost $nameOpt not found\033[0m"
 	fi
 
 else
 
 	index=0
-	for i in $name
+	echo "$name" |while read i 
 	do
 		index=`expr $index + 1`
 		address=`echo "$hostname" | head -$index | tail -1`
-		echo "\033[33m$index. \033[32;1m$i\033[0m ($address)"
+		echo -e "\033[33m$index. \033[32;1m$i\033[0m ($address)"
 	done
 
 	# Prompt for instance number(s)
@@ -151,7 +159,7 @@ do
   done
 
   # Run ssh
-  echo "\033[32mConnecting to $selectedname \033[0m"
-  echo "\033[33mssh -i $key $xOpt $user@$selectedhost\033[0m"
+  echo -e "\033[32mConnecting to $selectedname \033[0m"
+  echo -e "\033[33mssh -i $key $xOpt $user@$selectedhost\033[0m"
   ssh -o StrictHostKeyChecking=no -i $key $xOpt $user@$selectedhost $commandOpt
 done
